#prod
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/mkt_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: mkt
      password: mkt_sit
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8083
