
spring:
  datasource:
      url: jdbc:mysql://119.3.237.172:3306/mkt_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: mkt
      password: mkt_sit
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8084
